/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.elastic_fetcher_api.domain.db.tables.references


import com.kbalazsworks.elastic_fetcher_api.domain.db.tables.FlywaySchemaHistory
import com.kbalazsworks.elastic_fetcher_api.domain.db.tables.RunStates



/**
 * The table <code>public.flyway_schema_history</code>.
 */
val FLYWAY_SCHEMA_HISTORY: FlywaySchemaHistory = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

/**
 * The table <code>public.run_states</code>.
 */
val RUN_STATES: RunStates = RunStates.RUN_STATES
