/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.elastic_fetcher_api.domain.db


import com.kbalazsworks.elastic_fetcher_api.domain.db.tables.FlywaySchemaHistory
import com.kbalazsworks.elastic_fetcher_api.domain.db.tables.RunStates

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    val FLYWAY_SCHEMA_HISTORY: FlywaySchemaHistory get() = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

    /**
     * The table <code>public.run_states</code>.
     */
    val RUN_STATES: RunStates get() = RunStates.RUN_STATES

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
        RunStates.RUN_STATES
    )
}
