/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.elastic_fetcher_api.domain.db.keys


import com.kbalazsworks.elastic_fetcher_api.domain.db.tables.FlywaySchemaHistory
import com.kbalazsworks.elastic_fetcher_api.domain.db.tables.RunStates
import com.kbalazsworks.elastic_fetcher_api.domain.db.tables.records.FlywaySchemaHistoryRecord
import com.kbalazsworks.elastic_fetcher_api.domain.db.tables.records.RunStatesRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val FLYWAY_SCHEMA_HISTORY_PK: UniqueKey<FlywaySchemaHistoryRecord> = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), arrayOf(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK), true)
val RUN_STATES_PKEY: UniqueKey<RunStatesRecord> = Internal.createUniqueKey(RunStates.RUN_STATES, DSL.name("run_states_pkey"), arrayOf(RunStates.RUN_STATES.INDEX), true)
