/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.elastic_fetcher_api.domain.db.tables


import com.kbalazsworks.elastic_fetcher_api.domain.db.Public
import com.kbalazsworks.elastic_fetcher_api.domain.db.keys.RUN_STATES_PKEY
import com.kbalazsworks.elastic_fetcher_api.domain.db.tables.records.RunStatesRecord

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class RunStates(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, RunStatesRecord>?,
    parentPath: InverseForeignKey<out Record, RunStatesRecord>?,
    aliased: Table<RunStatesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<RunStatesRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.run_states</code>
         */
        val RUN_STATES: RunStates = RunStates()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<RunStatesRecord> = RunStatesRecord::class.java

    /**
     * The column <code>public.run_states.index</code>.
     */
    val INDEX: TableField<RunStatesRecord, String?> = createField(DSL.name("index"), SQLDataType.VARCHAR.nullable(false), this, "")

    /**
     * The column <code>public.run_states.timestamp</code>.
     */
    val TIMESTAMP: TableField<RunStatesRecord, Long?> = createField(DSL.name("timestamp"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.run_states.doc</code>.
     */
    val DOC: TableField<RunStatesRecord, Long?> = createField(DSL.name("doc"), SQLDataType.BIGINT.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<RunStatesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<RunStatesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<RunStatesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.run_states</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.run_states</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.run_states</code> table reference
     */
    constructor(): this(DSL.name("run_states"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<RunStatesRecord> = RUN_STATES_PKEY
    override fun `as`(alias: String): RunStates = RunStates(DSL.name(alias), this)
    override fun `as`(alias: Name): RunStates = RunStates(alias, this)
    override fun `as`(alias: Table<*>): RunStates = RunStates(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): RunStates = RunStates(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): RunStates = RunStates(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): RunStates = RunStates(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): RunStates = RunStates(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): RunStates = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): RunStates = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): RunStates = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): RunStates = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): RunStates = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): RunStates = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): RunStates = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): RunStates = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): RunStates = where(DSL.notExists(select))
}
