/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.elastic_fetcher_api.domain.db.tables.records


import com.kbalazsworks.elastic_fetcher_api.domain.db.tables.RunStates

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class RunStatesRecord() : UpdatableRecordImpl<RunStatesRecord>(RunStates.RUN_STATES) {

    open var index: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var timestamp: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var doc: Long?
        set(value): Unit = set(2, value)
        get(): Long? = get(2) as Long?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised RunStatesRecord
     */
    constructor(index: String? = null, timestamp: Long? = null, doc: Long? = null): this() {
        this.index = index
        this.timestamp = timestamp
        this.doc = doc
        resetChangedOnNotNull()
    }
}
